# Generated by Django 4.0.5 on 2022-07-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reparacion',
            old_name='tipo',
            new_name='tipo_rep',
        ),
        migrations.AddField(
            model_name='cliente',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_web.equipo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reparacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_web.reparacion'),
        ),
    ]
