# Generated by Django 4.0.5 on 2022-07-13 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0002_reparacion_orden_reparacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='orden_reparacion',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='telefono',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('orden_reparacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_web.reparacion')),
            ],
        ),
    ]
