# Generated by Django 4.0.5 on 2022-07-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0003_remove_reparacion_apellido_remove_reparacion_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='orden_reparacion',
        ),
    ]
